### ISSUE TITLE
Self-host compilation errors after stop and up again

### ISSUE THREAD

**Issue by raafael** [metz-sh/simulacrum#35]
In self host I close de browser and stop docker compose then after start up again I'm getting some compilation errors like it couldn't find Map or array types

error:Cannot find name 'Map'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

error:Property 'push' does not exist on type '{}'.

error:Property 'find' does not exist on type '{}'.

error:Property 'filter' does not exist on type '{}'.

How can I solve them?

**Comment by iostreamer-X** [comment]
Hey @raafael

When starting, the app loads core `.d.ts` files from a CDN. This errors usually happens when it's not able to fetch those. 

I have been following it since this issue popped up on sentry as well but rarely. And it goes away after a refresh(full preferably).

Can you please check:
- the console and network logs?
- for now, try a hard refresh?

Meanwhile, I will be working on bundling those files with the app itself so that it doesn't have load them from an unreliable CDN.

**Comment by raafael** [comment]
Hi @iostreamer-X !

Thank you for your fast reply, I stop docker clean cache and everything else in chrome but the problem persists.
The print below is from console and in network there is no call to .d.ts files.
![image](https://github.com/user-attachments/assets/68278e38-7410-4615-9b29-7069bcf88cc3)

So I tried open chrome in private navigation then I notice the .d.ts files load in network tab.

When you said try a hard refresh that is a command that I can do that I'm missing?

**Comment by iostreamer-X** [comment]
I think cleaning cache is the equivalent of hard refresh.

I tried to reproduce it locally but no luck. Any chance you can share the code?

**Comment by raafael** [comment]
Hy @iostreamer-X  I did a pull from seflhost, build and deploy it into our k8s and it seems to me that is every thing work.
Thank you for your amazing job
